spring.application.name=Seguradora-NQN
spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=db_seguradora_nqn;encrypt=false;trustServerCertificate=true}

# A senha deve ser definida em variaveis de ambiente, para o docker-compose se responsabilizar pela criação do banco.
spring.datasource.username=sa
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

#Se o banco não existir poderá ser criado
spring.jpa.properties.hibernate.javax.persistence.schema-generation.create-database-schemas=true